app-title: Griphitor
app-icon: assets/icon.ico
menubar-tearoff: false
theme: monokai-plus-plus
# You can add you own custom theme and font here
block-cursor: false
code_font: Firacode NF
code_font_size: 12
themes:
- assets/themes/azure.json
- assets/themes/darcula.json
- assets/themes/monokai.json
- assets/themes/monokai-plus-plus.json

file-extensions_name: Html Webpage document
default-extension: '*.html'
file-extensions:
- '*.html'
- '*.htm'
- '*.xhtml'
